# ==================================================
# INTUITIVES DAW - NEOBRUTALIST SYSTEM THEME
# "Does this sound cool?" - The only rule.
# ==================================================

daw:
  # Item editor CC/pitchbend automation point
  item_atm_point: "#FFEE33"
  # The pen drawing the outline of an item editor CC/pitchbend automation point
  item_atm_point_pen: "#1A1A1F"
  # Item editor selected CC/pitchbend automation point
  item_atm_point_selected: "#FFFEF0"
  # Item editor audio item handle
  item_audio_handle: "{{ item_handle }}"
  # Item editor selected audio item handle
  item_audio_handle_selected: "#1A1A1F"
  # The horizontal line that is drawn on audio items during
  # volume manipulation using mouse click+drag with
  # modifier keys.  The item will be selected, so this color
  # must contrast with the selected audio item color
  item_audio_vol_line: "#FF3366"
  # The text on an audio item that displays data such as file
  # name, and volume during mouse modifier operations.  The item
  # will be selected, this color must contrast with the selected
  # audio item color
  item_audio_label: "{{ text_color }}"
  # The text on an audio item that displays data such as file name, and volume
  # during mouse modifier operations.  The item will be selected, this color
  # must contrast with the selected color
  item_audio_label_selected: "#1A1A1F"
  # The color used to draw the audio file waveform onto the audio item
  item_audio_waveform: "#6366F1"
  # The background of the note editor for the keys that are not part of
  # the current scale
  note_black_background: "#1A1A1F"
  # The background of the note editor for the root key of the current scale
  note_root_background: "#3D1515"
  # The background of the note editor for the keys that are part of the
  # current scale
  note_white_background: "#2F2F3A"
  # The vertical lines drawn between beats according to snap settings
  # ie: 1/16th, 1/8th note, etc...
  note_snap_line: "#4A4A4F"
  # The vertical line drawn at each beat
  note_beat_line: "#6A6A6F"
  # The color of a selected note
  note_selected_color: "#FFFEF0"
  # The color of the note when velocity is at max value (Crimson - high energy)
  note_vel_max_color: "#FF3366"
  # The color of the note when velocity is at min value (Sapphire - calm)
  note_vel_min_color: "#3366FF"
  # The sequencer playback cursor
  playback_cursor: "#FFFEF0"
  # Enable antialiasing for the sequencer
  seq_antialiasing: true
  # Sequencer automation points (Sunburst highlight)
  seq_atm_item: "#FFEE33"
  # Selected sequencer automation points
  seq_atm_item_selected: "#1A1A1F"
  # Sequencer automation lines
  seq_atm_line: "#FFEE33"
  # Sequencer QGraphicsScene background
  seq_background: "#1A1A1F"
  # The background fill color of the sequencer items
  # If seq_item_background_use_track_color == true, the track color will be
  # used, and this value should be set to something with transparency
  seq_item_background: "#12666666"
  # Use the track color instead of seq_item_background
  seq_item_background_use_track_color: true
  # Vertical bar lines in the sequencer
  seq_bar_line: "#FFFEF0"
  # Vertical beat lines in the sequencer
  seq_beat_line: "#4A4A4F"
  # Vertical 16th note lines in the sequencer
  seq_16th_line: "#2F2F3A"
  # Sequencer header (panel background)
  seq_header: "#252530"
  # Sequencer header context menu event position marker
  seq_header_event_pos: "#FFEE33"
  # Sequencer header region (Electric Indigo primary)
  seq_header_region: "#6366F1"
  # Sequencer header text
  seq_header_text: "#FFFEF0"
  # Sequencer item handle
  seq_item_handle: "{{ item_handle }}"
  # Sequencer selected item handle
  seq_item_handle_selected: "#252530"
  # Used to paint audio on sequencer items
  seq_item_audio: "#B0B0B5"
  # Used to paint notes on sequencer items
  seq_item_note: "#FFFEF0"
  # The label text for sequencer items
  seq_item_text: "#FFFEF0"
  # The label text for selected sequencer items
  seq_item_text_selected: "#1A1A1F"
  # Selected sequencer items (Sunburst highlight)
  seq_selected_item: "#FFEE33"
  # Sequencer tempo marker
  seq_tempo_marker: "#FF3366"
  # Horizontal track lines in the sequencer
  seq_track_line: "#4A4A4F"
  # The silhouette when dragging an item onto a view
  drag_drop_silhouette: "#6366F1"
  # Default track colors - Chromasynesthesia inspired
  track_default_colors:
    - "#33FF66" # Emerald
    - "#33EEFF" # Cyan
    - "#3366FF" # Sapphire
    - "#6366F1" # Electric Indigo
    - "#A855F7" # Violet
    - "#FF3366" # Crimson
    - "#FF9933" # Tangerine
    - "#FFEE33" # Sunburst

widgets:
  # The color that audio files are drawn with in the sampler and wave editor
  audio_item_viewer_color: "#6366F1"
  # The default QGraphicsScene background color used by the widgets library
  default_scene_background: "#1A1A1F"
  # Used to draw the arc around the knob (Electric Indigo primary)
  knob_arc_pen: "#6366F1"
  # Used to draw the knob background
  knob_arc_background_pen: "#4A4A4F"
  # The knob background image
  knob_bg_image: "knob-bg.svg"
  # The knob image.  Will be rotated as the knob moves
  knob_fg_image: "knob-fg.svg"
  # The gradient used to draw peak meters - Chromasynesthesia gradient
  peak_meter:
    stops:
      - pos: 0.0
        color: "#FF3366" # Crimson (clipping)
      - pos: 0.1
        color: "#FF9933" # Tangerine (hot)
      - pos: 0.3
        color: "#FFEE33" # Sunburst (optimal)
      - pos: 0.6
        color: "#33FF66" # Emerald (good)
      - pos: 0.9
        color: "#3366FF" # Sapphire (low)
  # The color of a playback cursor line
  playback_cursor: "#FFFEF0"
  # Routing graph widget node (Electric Indigo)
  rout_graph_node: "#6366F1"
  # Routing graph widget node text
  rout_graph_node_text: "#FFFEF0"
  # Routing graph widget to node when mouse hovering
  rout_graph_to: "#FF3366"
  # Routing graph widget from node when mouse hovering
  rout_graph_from: "#33FF66"
  # Routing graph widget matrix lines
  rout_graph_lines: "#4A4A4F"
  # Routing graph wires connecting audio
  rout_graph_wire_audio: "#33FF66"
  # Routing graph wires connecting midi
  rout_graph_wire_midi: "#6366F1"
  # Routing graph wires connecting audio sidechain inputs
  rout_graph_wire_sc: "#FF3366"
  # Splash screen shown at start up
  splash_screen: "splash.svg"
  # Text status messages on splash screen shown at start up
  splash_screen_text: "#FFFEF0"
